# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0004_auto_20170724_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='assignedTo',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(),
        ),
    ]
